/* This file was generated by syncqt. */
#ifndef QT_QTQML_VERSION_H
#define QT_QTQML_VERSION_H

#define QTQML_VERSION_STR "5.9.3"

#define QTQML_VERSION 0x050903

#endif // QT_QTQML_VERSION_H
