/* This file was generated by syncqt. */
#ifndef QT_QTSERIALBUS_VERSION_H
#define QT_QTSERIALBUS_VERSION_H

#define QTSERIALBUS_VERSION_STR "5.9.3"

#define QTSERIALBUS_VERSION 0x050903

#endif // QT_QTSERIALBUS_VERSION_H
